name: "Build Python Wheels"
description: "Build wheels for pip libraries that require being built from source"
author: "Mel Massadian"

inputs:
  wheels:
    description: "Comma separated list of wheels to build"
    required: true
  python-version:
    description: "The version of Python to install"
    required: false
    default: "3.10"
  requirements-file:
    description: "The path to the requirements.txt file"
    required: false
  dependencies:
    description: "Inline array of dependencies to install"
    required: false

outputs:
  wheel_paths:
    description: "JSON string of the list of wheels"
    value: ${{ steps.build-wheels.outputs.wheel_paths }}

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Dependencies
      run: |
        if [ -n "${{ inputs.dependencies }}" ]; then
          pip install ${{ inputs.dependencies }}
        fi
        if [ -n "${{ inputs.requirements-file }}" ]; then
        pip install -r ${{ inputs.requirements-file }}
        fi
        if [ -f requirements.txt ]; then
        pip install -r requirements.txt
        fi
      shell: bash

    - name: Analyze & Build wheels
      id: build-wheels
      run: python ${GITHUB_ACTION_PATH}/src/main.py
      shell: bash
      env:
        WHEELS: ${{ inputs.wheels }}
