name: "Free Disk Space"
description: "Frees up disk space on GitHub runners by removing unnecessary packages and directories"
inputs:
  remove-dotnet:
    description: "Remove .NET packages and directories"
    required: false
    default: "true"
  remove-llvm:
    description: "Remove LLVM packages"
    required: false
    default: "true"
  remove-php:
    description: "Remove PHP packages"
    required: false
    default: "true"
  remove-mongodb:
    description: "Remove MongoDB packages"
    required: false
    default: "true"
  remove-mysql:
    description: "Remove MySQL packages"
    required: false
    default: "true"
  remove-azure-cli:
    description: "Remove Azure CLI"
    required: false
    default: "true"
  remove-browsers:
    description: "Remove Chrome and Firefox browsers"
    required: false
    default: "true"
  remove-android:
    description: "Remove Android SDK"
    required: false
    default: "true"
  remove-haskell:
    description: "Remove Haskell/GHC"
    required: false
    default: "true"
  remove-powershell:
    description: "Remove PowerShell"
    required: false
    default: "true"
  custom-packages:
    description: "Additional packages to remove (space-separated)"
    required: false
    default: ""
  custom-directories:
    description: "Additional directories to remove (space-separated, absolute paths)"
    required: false
    default: ""
outputs:
  space-freed-kb:
    description: "Disk space freed in KB"
    value: ${{ steps.run-script.outputs.space-freed-kb }}
  space-freed-mb:
    description: "Disk space freed in MB"
    value: ${{ steps.run-script.outputs.space-freed-mb }}
  space-freed-gb:
    description: "Disk space freed in GB (with 2 decimal places)"
    value: ${{ steps.run-script.outputs.space-freed-gb }}
  initial-space:
    description: "Initial available disk space"
    value: ${{ steps.run-script.outputs.initial-space }}
  final-space:
    description: "Final available disk space"
    value: ${{ steps.run-script.outputs.final-space }}
runs:
  using: "composite"
  steps:
    - name: Free up disk space
      id: run-script
      shell: bash
      run: ${{ github.action_path }}/free-space.sh
      env:
        INPUT_REMOVE_DOTNET: ${{ inputs.remove-dotnet }}
        INPUT_REMOVE_LLVM: ${{ inputs.remove-llvm }}
        INPUT_REMOVE_PHP: ${{ inputs.remove-php }}
        INPUT_REMOVE_MONGODB: ${{ inputs.remove-mongodb }}
        INPUT_REMOVE_MYSQL: ${{ inputs.remove-mysql }}
        INPUT_REMOVE_AZURE_CLI: ${{ inputs.remove-azure-cli }}
        INPUT_REMOVE_BROWSERS: ${{ inputs.remove-browsers }}
        INPUT_REMOVE_ANDROID: ${{ inputs.remove-android }}
        INPUT_REMOVE_HASKELL: ${{ inputs.remove-haskell }}
        INPUT_REMOVE_POWERSHELL: ${{ inputs.remove-powershell }}
        INPUT_CUSTOM_PACKAGES: ${{ inputs.custom-packages }}
        INPUT_CUSTOM_DIRECTORIES: ${{ inputs.custom-directories }}
    
    # Set outputs for the action
    - name: Set action outputs
      shell: bash
      run: |
        # Get the values from the script's step
        # In composite actions, each step has its own output file
        # We need to extract the values from the free-space.sh step
        SPACE_FREED_KB=$(cat $GITHUB_OUTPUT | grep "^space-freed-kb=" | cut -d= -f2 || echo "")
        SPACE_FREED_MB=$(cat $GITHUB_OUTPUT | grep "^space-freed-mb=" | cut -d= -f2 || echo "")
        SPACE_FREED_GB=$(cat $GITHUB_OUTPUT | grep "^space-freed-gb=" | cut -d= -f2 || echo "")
        INITIAL_SPACE=$(cat $GITHUB_OUTPUT | grep "^initial-space=" | cut -d= -f2 || echo "")
        FINAL_SPACE=$(cat $GITHUB_OUTPUT | grep "^final-space=" | cut -d= -f2 || echo "")
        
        # Set the outputs for this step
        echo "space-freed-kb=$SPACE_FREED_KB" >> $GITHUB_OUTPUT
        echo "space-freed-mb=$SPACE_FREED_MB" >> $GITHUB_OUTPUT
        echo "space-freed-gb=$SPACE_FREED_GB" >> $GITHUB_OUTPUT
        echo "initial-space=$INITIAL_SPACE" >> $GITHUB_OUTPUT
        echo "final-space=$FINAL_SPACE" >> $GITHUB_OUTPUT
        
        echo "DEBUG: Set outputs for the action:"
        echo "- space-freed-kb: $SPACE_FREED_KB"
        echo "- space-freed-mb: $SPACE_FREED_MB"
        echo "- space-freed-gb: $SPACE_FREED_GB"
        echo "- initial-space: $INITIAL_SPACE"
        echo "- final-space: $FINAL_SPACE"
      id: outputs
