name: "Free Disk Space"
description: "Frees up disk space on GitHub runners by removing unnecessary packages and directories"
inputs:
  remove-dotnet:
    description: "Remove .NET packages and directories"
    required: false
    default: "true"
  remove-llvm:
    description: "Remove LLVM packages"
    required: false
    default: "true"
  remove-php:
    description: "Remove PHP packages"
    required: false
    default: "true"
  remove-mongodb:
    description: "Remove MongoDB packages"
    required: false
    default: "true"
  remove-mysql:
    description: "Remove MySQL packages"
    required: false
    default: "true"
  remove-azure-cli:
    description: "Remove Azure CLI"
    required: false
    default: "true"
  remove-browsers:
    description: "Remove Chrome and Firefox browsers"
    required: false
    default: "true"
  remove-android:
    description: "Remove Android SDK"
    required: false
    default: "true"
  remove-haskell:
    description: "Remove Haskell/GHC"
    required: false
    default: "true"
  remove-powershell:
    description: "Remove PowerShell"
    required: false
    default: "true"
  custom-packages:
    description: "Additional packages to remove (space-separated)"
    required: false
    default: ""
  custom-directories:
    description: "Additional directories to remove (space-separated, absolute paths)"
    required: false
    default: ""
outputs:
  space-freed-kb:
    description: "Disk space freed in KB"
  space-freed-mb:
    description: "Disk space freed in MB"
  space-freed-gb:
    description: "Disk space freed in GB (with 2 decimal places)"
  initial-space:
    description: "Initial available disk space"
  final-space:
    description: "Final available disk space"
runs:
  using: "composite"
  steps:
    - name: Free up disk space
      shell: bash
      run: ${{ github.action_path }}/free-space.sh
      env:
        INPUT_REMOVE_DOTNET: ${{ inputs.remove-dotnet }}
        INPUT_REMOVE_LLVM: ${{ inputs.remove-llvm }}
        INPUT_REMOVE_PHP: ${{ inputs.remove-php }}
        INPUT_REMOVE_MONGODB: ${{ inputs.remove-mongodb }}
        INPUT_REMOVE_MYSQL: ${{ inputs.remove-mysql }}
        INPUT_REMOVE_AZURE_CLI: ${{ inputs.remove-azure-cli }}
        INPUT_REMOVE_BROWSERS: ${{ inputs.remove-browsers }}
        INPUT_REMOVE_ANDROID: ${{ inputs.remove-android }}
        INPUT_REMOVE_HASKELL: ${{ inputs.remove-haskell }}
        INPUT_REMOVE_POWERSHELL: ${{ inputs.remove-powershell }}
        INPUT_CUSTOM_PACKAGES: ${{ inputs.custom-packages }}
        INPUT_CUSTOM_DIRECTORIES: ${{ inputs.custom-directories }}
    
    # Set outputs directly
    - name: Set action outputs
      shell: bash
      run: |
        # Get values from the script output
        SPACE_FREED_KB=$(cat $GITHUB_OUTPUT | grep "space-freed-kb=" | cut -d= -f2)
        SPACE_FREED_MB=$(cat $GITHUB_OUTPUT | grep "space-freed-mb=" | cut -d= -f2)
        SPACE_FREED_GB=$(cat $GITHUB_OUTPUT | grep "space-freed-gb=" | cut -d= -f2)
        INITIAL_SPACE=$(cat $GITHUB_OUTPUT | grep "initial-space=" | cut -d= -f2)
        FINAL_SPACE=$(cat $GITHUB_OUTPUT | grep "final-space=" | cut -d= -f2)
        
        # Debug values
        echo "DEBUG: Values from script output:"
        echo "SPACE_FREED_KB=$SPACE_FREED_KB"
        echo "SPACE_FREED_MB=$SPACE_FREED_MB"
        echo "SPACE_FREED_GB=$SPACE_FREED_GB"
        echo "INITIAL_SPACE=$INITIAL_SPACE"
        echo "FINAL_SPACE=$FINAL_SPACE"
        
        # Create a new output file for this step
        echo "space-freed-kb=$SPACE_FREED_KB" >> $GITHUB_OUTPUT
        echo "space-freed-mb=$SPACE_FREED_MB" >> $GITHUB_OUTPUT
        echo "space-freed-gb=$SPACE_FREED_GB" >> $GITHUB_OUTPUT
        echo "initial-space=$INITIAL_SPACE" >> $GITHUB_OUTPUT
        echo "final-space=$FINAL_SPACE" >> $GITHUB_OUTPUT
      id: outputs
